[window]
decorations = "None"

[window.padding]
x = 10
y = 10

[colors.primary]
background = '#2f383e'
foreground = '#d3c6aa'

[colors.normal]
black   = '#4b565c'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#4b565c'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
